export {
    RESOURCE_MANAGEMENT_SIGN_UP_PATH,
    RESOURCE_MANAGEMENT_SIGN_IN_PATH,
    RESOURCE_MANAGEMENT_ADMIN_DASHBOARD_PATH,
    USER_DASHBOARD_PATH
}
from './RouteConstants';
//export { RESOURCE_MANAGEMENT_SIGN_UP_PATH, RESOURCE_MANAGEMENT_SIGN_IN_PATH, RESOURCE_MANAGEMENT_ADMIN_DASHBOARD_PATH };
